# Generated by Django 5.0.3 on 2025-04-27 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAIBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='travelPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonForTravel', models.CharField(default='Vacation', max_length=200)),
                ('budget', models.CharField(default='Luxury', max_length=200)),
                ('accomodation', models.CharField(default='Hotel', max_length=200)),
                ('destinationType', models.CharField(default='The City', max_length=200)),
                ('flightDuration', models.CharField(default='Short-Haul Flights', max_length=200)),
                ('weather', models.CharField(default='Snowy', max_length=200)),
                ('travelCompanions', models.CharField(default='Solo', max_length=200)),
                ('flightPriority', models.CharField(default='Lowest Price', max_length=200)),
                ('favouriteActivities', models.CharField(default='restaurant', max_length=500)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelAIBackend.users')),
            ],
        ),
    ]
