# Generated by Django 5.0.3 on 2025-02-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAIBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='JohnDoe123@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='firstName',
            field=models.CharField(default='John', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='Doe', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='Calculator123!', max_length=200),
        ),
    ]
