# Generated by Django 5.0.3 on 2025-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAIBackend', '0002_users_email_users_firstname_users_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='The Museum', max_length=200)),
            ],
        ),
    ]
