# Generated by Django 5.0.3 on 2025-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAIBackend', '0002_travelpref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpref',
            name='favouriteActivities',
            field=models.JSONField(default=list),
        ),
    ]
