# Generated by Django 5.0.3 on 2025-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelAIBackend', '0004_attractions_iswheelchairaccessible'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='city',
            field=models.CharField(default='London', max_length=200),
        ),
    ]
